### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by OlegKrikun** [OzymandiasTheGreat/emoji-keyboard#10]
This app crashed on gnome wayland session:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Xlib/xauth.py", line 42, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/oleg/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 15, in <module>
    from emoji_keyboard import emoji_lib
  File "/usr/lib/python3.5/dist-packages/emoji_keyboard/emoji_lib.py", line 32, in <module>
    local_display = display.Display()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/lib/python3/dist-packages/Xlib/support/connect.py", line 93, in get_auth
    return getattr(mod, modname).get_auth(sock, dname, host, dno)
  File "/usr/lib/python3/dist-packages/Xlib/support/unix_connect.py", line 116, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/lib/python3/dist-packages/Xlib/xauth.py", line 44, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/oleg/.Xauthority'
```

**Comment by OzymandiasTheGreat** [comment]
There's no plans to add wayland support, at least for now, as emoji-keyboard depends heavily on X server.

**Comment by OzymandiasTheGreat** [comment]
Ok, so I have removed explicit dependencies on X. This should run at least on xwayland, at least in theory.
Can't test myself, as I can't get wayland to run at all.

**Comment by OzymandiasTheGreat** [comment]
Wayland is tested and mostly supported since version 2.3.0.
Since gnome under wayland doesn't respect no-focus property keyboard window is hidden for a sec after every selection.
Also, window moving doesn't work (at least under gnome on wayland) so where the keyboard will reappear depends solely on the window manager.
Search fully works as intended, although where the window will appear is, again, out of my control.
Check the README for installation instructions , as installation under wayland requires extra steps.
