### ISSUE TITLE
emoji-keyboard requires evdev pkg-info to be an actual file

### ISSUE THREAD

**Issue by juanitotc** [OzymandiasTheGreat/emoji-keyboard#17]
I'm trying to package emoji-keyboard for tinycorelinux - this uses a squashfs package loop mounted and symlinked to the root file system.

It appears that emoji-keyboard requires the evdev pkg-info file to be an actual file - since I doubt it wants to change the file, why is this and can it be fixed?

Details below:

$ ls -l /usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info/PKG-INFO
lrwxrwxrwx    1 root     root           114 Oct 29 16:05 /usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info/PKG-INFO -> /tmp/tcloop/python3.6-evdev/usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info/PKG-INFO
$ emoji-keyboard
Traceback (most recent call last):
  File "/usr/local/bin/emoji-keyboard", line 4, in <module>
    __import__('pkg_resources').run_script('emoji-keyboard==2.2.0', 'emoji-keyboard')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 650, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 643, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 699, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2023, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2432, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2772, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2397, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2565, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1467, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1576, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info/PKG-INFO'

$ sudo cp /tmp/tcloop/python3.6-evdev/usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info/PKG-INFO /usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info
$ sudo chmod 664 /usr/local/lib/python3.6/site-packages/evdev-0.7.0-py3.6-linux-x86_64.egg-info/PKG-INFO

..and now things work.

**Comment by OzymandiasTheGreat** [comment]
How did you install emoji-keyboard?
emoji-keyboard doesn't access or care about said file at all and judging from the traceback you posted
`/usr/local/bin/emoji-keyboard` is NOT the main emoji-keyboard script but a wrapper that launches the main script. Your issue is with this wrapper, but I have no clue which installation method creates such wrapper rather than plainly extracting files to correct locations.

**Comment by OzymandiasTheGreat** [comment]
No activity, closing this.
