### ISSUE TITLE
Error installing via pip (FileNotFoundError:)

### ISSUE THREAD

**Issue by gitowiec** [OzymandiasTheGreat/emoji-keyboard#37]
I can't install it on Ubuntu Budgie 18.04 via pip3, heres the error:
```
marek@latitude:~/tmp$ sudo -H pip3 install ./master.zip
Processing ./master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tc2zl7hc-build/setup.py", line 5, in <module>
        from lib.emoji_shared import version
      File "/tmp/pip-tc2zl7hc-build/lib/emoji_shared.py", line 102, in <module>
        wayland = check_wayland()
      File "/tmp/pip-tc2zl7hc-build/lib/emoji_shared.py", line 82, in check_wayland
        current_user = current_user if current_user != 'root' else os.getlogin()
    FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by OzymandiasTheGreat** [comment]
New version, AppImage, no installation, use that.
As an aside, this is Wayland detection code and it's buggy. Like Wayland itself.
