### ISSUE TITLE
Error running `emoji-keyboard -h` from CLI

### ISSUE THREAD

**Issue by gitowiec** [OzymandiasTheGreat/emoji-keyboard#38]
On Ubuntu Budgie 18.04, here is the error message:
```
marek@latitude:~/tmp$ emoji-keyboard -h
Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 15, in <module>
    from emoji_keyboard import emoji_lib
ModuleNotFoundError: No module named 'emoji_keyboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 17, in <module>
    from lib import emoji_lib
ModuleNotFoundError: No module named 'lib'
```
PS: I installed emoji-keyboard using ppa because couldn't install via pip (https://github.com/OzymandiasTheGreat/emoji-keyboard/issues/37)

**Comment by gustawdaniel** [comment]
I had the same error.

**Comment by danger89** [comment]
Me too, I just installed it via PPA. Executing its just not working:

```
emoji-keyboard 
Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 15, in <module>
    from emoji_keyboard import emoji_lib
ModuleNotFoundError: No module named 'emoji_keyboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 17, in <module>
    from lib import emoji_lib
ModuleNotFoundError: No module named 'lib'

```

**Comment by varunharidas** [comment]
Same issue any fixes? I'm on Gallium

**Comment by OzymandiasTheGreat** [comment]
Command line switches are no longer supported since you can set hotkeys in the app proper.
Closing this since it's no longer applicable.
