### ISSUE TITLE
Appimage die on start

### ISSUE THREAD

**Issue by Flashwalker** [OzymandiasTheGreat/emoji-keyboard#69]
No working Appimage version.

# v3.1.1
```
$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Загрузки/emoji-keyboard-3.1.1.AppImage
Parent pid 206969, child pid 206970

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Child process initialized in 55.24 ms
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[2:1207/223734.348088:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.

Parent is shutting down, bye...
AppImage detached
```
![2022-12-07_22-38-17](https://user-images.githubusercontent.com/2188215/206223601-b7611561-a3e1-4f68-99f6-4376265d39b0.png)

# v4.0.0
```
$ firejail --env=DESKTOPINTEGRATION=appimaged --noprofile --appimage /home/user/Загрузки/emoji-keyboard_4.0.0_amd64.AppImage
Parent pid 206451, child pid 206452

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Child process initialized in 44.95 ms
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/ozymandias/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-utils-1.0.3/src/lib.rs:135:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Parent is shutting down, bye...
AppImage detached

```

```
$ env RUST_BACKTRACE=1 firejail --env=DESKTOPINTEGRATION=appimaged --env=RUST_BACKTRACE=1 --noprofile --appimage /home/user/Загрузки/emoji-keyboard_4.0.0_amd64.AppImage
Parent pid 208851, child pid 208852

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Child process initialized in 60.41 ms
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/ozymandias/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-utils-1.0.3/src/lib.rs:135:11
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: <tauri_utils::Env as core::default::Default>::default
   3: tauri::app::Builder<R>::build
   4: emoji_keyboard::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Parent is shutting down, bye...
AppImage detached
```

```
$ env RUST_BACKTRACE=full firejail --env=DESKTOPINTEGRATION=appimaged --env=RUST_BACKTRACE=full --noprofile --appimage /home/user/Загрузки/emoji-keyboard_4.0.0_amd64.AppImage
Parent pid 209182, child pid 209183

** Warning: dropping all Linux capabilities and setting NO_NEW_PRIVS prctl **

Mounting appimage type 2
Child process initialized in 50.33 ms
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/ozymandias/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-utils-1.0.3/src/lib.rs:135:11
stack backtrace:
   0:     0x5575eb68ec6d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5575eb68ec6d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5575eb68ec6d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5575eb68ec6d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5575eb6b325c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x5575eb68b8b1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x5575eb690465 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5575eb690465 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5575eb690465 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x5575eb690181 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x5575eb6909f6 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x5575eb6908a9 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:586:13
  12:     0x5575eb68f164 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5575eb690619 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x5575eb353af3 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x5575eb5b3b8b - <tauri_utils::Env as core::default::Default>::default::hfba78dd26bb91e86
  16:     0x5575eb3f6c05 - tauri::app::Builder<R>::build::hc065e7836cbd5b4e
  17:     0x5575eb3c3c91 - emoji_keyboard::main::h0db0a3b33fde396b
  18:     0x5575eb41f333 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd249f80af6fd81e8
  19:     0x5575eb46c849 - std::rt::lang_start::{{closure}}::h65dcd20c55eb9cf6
  20:     0x5575eb686d6e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  21:     0x5575eb686d6e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  22:     0x5575eb686d6e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  23:     0x5575eb686d6e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  24:     0x5575eb686d6e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  25:     0x5575eb686d6e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  26:     0x5575eb686d6e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  27:     0x5575eb686d6e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  28:     0x5575eb686d6e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  29:     0x5575eb3c53e2 - main
  30:     0x7f4a74629d90 - <unknown>
  31:     0x7f4a74629e40 - __libc_start_main
  32:     0x5575eb353f15 - _start
  33:                0x0 - <unknown>

Parent is shutting down, bye...
AppImage detached
```

**Comment by faveoled** [comment]
Runs without firejail (4.0.0)
